[package]
name = "snarkos"
version = "0.8.0"
authors = ["Michael Beller", "Collin Chin", "Raymond Chu", "Matthew Green", "Ian Miers", "Howard Wu"]
description = "A decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
    "algorithms",
    "benchmarks",
    "console",
    "curves",
    "dpc",
    "errors",
    "gadgets",
    "models",
    "objects",
    "profiler",
    "dpc_storage",
    "dpc_consensus",
    "dpc_network",
    "utilities"
]

[lib]
name = "dpc_node"
path = "dpc_node/lib.rs"

[[bin]]
name = "snarkos"
path = "dpc_node/main.rs"

[dependencies]
snarkos-dpc = { path = "./dpc" }
snarkos-dpc-consensus = { path = "./dpc_consensus" }
snarkos-errors = { path = "./errors", version = "0.8.0", default-features = false, features = ["node"] }
snarkos-dpc-network = { path = "./dpc_network" }
snarkos-objects = { path = "objects" }
#snarkos-rpc = { path = "./rpc" }
snarkos-dpc-storage = { path = "./dpc_storage" }
snarkos-utilities = { path = "./utilities" }

clap = { version = "2.33.0" }
env_logger = { version = "0.7.1" }
hex = { version = "0.4.1" }
log = { version = "0.4.8" }
rand = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
rusty-hook = { version = "0.10.3" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true
