[workspace]
members = [
    "benchmarks",
    "consensus",
    "metrics",
    "network",
    "posw",
    "profiler",
    "rpc",
    "storage",
    "testing",
    "toolkit",
]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3 # necessary for DPC testing
lto = "thin"
incremental = true
debug-assertions = true
debug = true
