[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
aleo-std = { version = "0.1.14", default-features = false }
anyhow = { version = "1.0" }
backoff = { version = "0.4", features = ["tokio"] }
bytes = { version = "1" }
colored = { version = "2.0" }
dotenv = { version = "0.15" }
futures = { version = "0.3" }
hyper = { version = "0.14" }
hyper-tls = { version = "0.5" }
indexmap = { version = "1.9", features = ["rayon"] }
once_cell = { version = "1.13.0" }
parking_lot = { version = "0.12" }
rand = { version = "0.8" }
rayon = { version = "1.5" }
rusoto_core = { version = "0.48" }
rusoto_s3 = { version = "0.48" }
serde_json = { version = "1.0" }
tokio = { version = "1.5.0", features = ["full"] }
tokio-util = { version = "0.7.3" }
tracing = { version = "0.1" }
warp = { version = "0.3" }

[dependencies.clap]
version = "3.1"
features = [ "derive" ]

[dependencies.tracing-subscriber]
version = "0.3"
features = [ "env-filter", "parking_lot" ]

[dependencies.snarkvm]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "7555dc0"
features = ["circuit", "console", "parallel", "utilities"]

[dependencies.bincode]
version = "1.0"

[dependencies.reqwest]
version = "0.11.11"

[dependencies.rocksdb]
version = "0.19"
default-features = false
features = [ "lz4" ]

[dependencies.serde]
version = "1"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.tempfile]
version = "3.2"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
