[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [ ".integration", "environment", "metrics", "network", "rpc", "storage", "utilities" ]

[dependencies]
crossterm = "0.23"
tui = "0.17.0"

  [dependencies.snarkos-environment]
  path = "./environment"
  version = "2.0.2"

  [dependencies.snarkos-metrics]
  path = "./metrics"
  version = "2.0.2"
  optional = true

  [dependencies.snarkos-network]
  path = "./network"
  version = "2.0.2"

  [dependencies.snarkos-rpc]
  path = "./rpc"
  version = "2.0.2"
  optional = true

  [dependencies.snarkos-storage]
  path = "./storage"
  version = "2.0.2"

  [dependencies.snarkos-utilities]
  path = "utilities"
  version = "2.0.2"

  [dependencies.snarkvm]
  version = "0.8.0"

  [dependencies.aleo-std]
  version = "0.1.6"

  [dependencies.anyhow]
  version = "1"

  [dependencies.colored]
  version = "2.0"

  [dependencies.num_cpus]
  version = "1"

  [dependencies.once_cell]
  version = "1"

  [dependencies.parking_lot]
  version = "0.12"

  [dependencies.rand]
  version = "0.8"

  [dependencies.rayon]
  version = "1"

  [dependencies.self_update]
  version = "0.28"
  features = [
    "archive-zip",
    "compression-zip-bzip2",
    "compression-zip-deflate",
    "compression-flate2"
  ]

  [dependencies.structopt]
  version = "0.3"

  [dependencies.thiserror]
  version = "1.0"

  [dependencies.tokio]
  version = "1"

  [dependencies.tracing]
  version = "0.1"

  [dependencies.tracing-subscriber]
  version = "0.3"
  features = [ "env-filter", "parking_lot" ]

[dev-dependencies.jsonrpsee]
version = "0.9"
features = [ "http-client" ]

[dev-dependencies.rusty-hook]
version = "0.11"

[features]
default = [ "rpc" ]
cuda = [ "snarkvm/cuda" ]
prometheus = [ "snarkos-metrics" ]
rpc = [ "snarkos-rpc" ]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = false

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
