[package]
name = "snarkos-network"
version = "0.1.0"
authors = ["raychu86"]
edition = "2018"

[dependencies]
snarkos-consensus = { path = "../consensus" }
snarkos-errors = { path = "../errors" }
snarkos-objects = { path = "../objects" }
snarkos-storage = { path = "../storage" }

bincode = { version = "1.2.0" }
byteorder = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
futures = { version = "0.1" }
hex = { version = "0.4.0" }
log = { version = "0.4.8" }
rand = { version = "0.7.3" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
#tokio-util = { version = "0.2.0", features = ["codec"]}
wagyu-bitcoin = { version = "0.6.1" }

[dev-dependencies]
tokio-test = { version = "0.2.0" }
serial_test = "*"
futures-await-test = { version = "0.3.0" }
