[package]
name = "snarkos-algorithms"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Algorithms for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[[example]]
name = "gm17"
path = "examples/snark/gm17.rs"
required-features = ["rand", "snarkos-curves/bls12_377", "snarkos-models/gadgets"]

[dependencies]
snarkos-errors = { path = "../errors", version = "0.8.0", default-features = false, features = ["algorithms"] }
snarkos-models = { path = "../models", version = "0.8.0", default-features = false, features = ["algorithms", "gadgets"] }
snarkos-profiler = { path = "../profiler", version = "0.8.0", default-features = false }
snarkos-utilities = { path = "../utilities", version = "0.8.0" }

blake2 = { version = "0.7", optional = true }
derivative = { version = "1" }
digest = { version = "0.7", optional = true }
rand = { version = "0.7", default-features = false, optional = true }
rayon = { version = "1", optional = true }
sha2 = { version = "0.8", optional = true }
smallvec = { version = "1.2", optional = true }

[dev-dependencies]
snarkos-curves = { path = "../curves", version = "0.8.0", default-features = false }

criterion = { version = "0.3.1" }
csv = { version = "1" }
rand_xorshift = { version = "0.2" }

#
# Each module in `snarkos-algorithms` is guarded by a feature flag to minimize compilation resources.
# To include any one of the modules in `snarkos-algorithms`, simply include its corresponding feature flag.
#
# For example, to include commitments for `snarkos-gadgets`, add the "commitment" feature as follows:
# snarkos-algorithms = { version = "x.x.x", default-features = false, features = ["commitment"] }
#
[features]
default = []
commitment = ["blake2", "crh", "digest"]
crh = ["rand", "rayon", "sha2"]
fft = ["rand", "rayon"]
merkle_tree = ["rand"]
msm = ["rand"]
prf = ["blake2", "digest"]
signature = ["blake2", "digest"]
snark = ["fft", "msm", "rand", "smallvec"]

print-trace = [ "snarkos-profiler/print-trace" ]
