[package]
name = "snarkos-node-narwhal-committee"
version = "2.1.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A committee for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
prop-tests = [ "rand", "rand_chacha", "snarkos-account", "test-strategy", "proptest", "anyhow" ]
test-helpers = [ "rand_distr" ]

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.snarkvm]
workspace = true

[dependencies.anyhow]
version = "1.0.71"
optional = true

[dependencies.proptest]
version = "1.0.0"
optional = true

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.rand_chacha]
version = "0.3"
optional = true

[dependencies.rand_distr]
version = "0.4"
optional = true

[dependencies.snarkos-account]
path = "../../../account"
version = "=2.1.4"
optional = true

[dependencies.test-strategy]
git = "https://github.com/frozenlib/test-strategy/"
branch = "master"
optional = true

[dev-dependencies.parking_lot]
version = "0.12"

[dev-dependencies.rand_distr]
version = "0.4"

[dev-dependencies.rayon]
version = "1"

[dev-dependencies.snarkos-node-narwhal-committee]
path = "."
features = [ "prop-tests" ]
