[package]
name = "snarkos-errors"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Errors for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
bincode = { version = "1.2.0", optional = true }
failure = { version = "0.1.7" }
hex = { version = "0.4.2", optional = true }
jsonrpc-core = { version = "14.0.5", optional = true }
rocksdb = { version = "0.13.0", optional = true }

#
# Each module in `snarkos-errors` is guarded by a feature flag to minimize compilation resources.
# To include any one of the modules in `snarkos-errors`, simply include its corresponding feature flag.
#
# For example, to include errors for `snarkos-algorithms`, add the "algorithms" feature as follows:
# snarkos-errors = { version = "x.x.x", default-features = false, features = ["algorithms"] }
#
[features]
default = []
algorithms = ["curves"]
consensus = []
curves = []
dpc = ["storage"]
gadgets = []
network = ["bincode"]
node = []
objects = ["hex"]
rpc = ["hex", "jsonrpc-core"]
storage = ["bincode", "hex", "rocksdb"]
