[package]
name = "snarkos-node-narwhal-ledger-service"
version = "2.1.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A ledger service for the memory pool in a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
mock = [ "tracing" ]

[dependencies.snarkvm]
workspace = true

[dependencies.tracing]
version = "0.1"
optional = true
