name: CI - Branches
on:
  push:
    branches-ignore:
      - 'master'
env:
  RUST_BACKTRACE: 1

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Check Tests (Simple)
    runs-on: [self-hosted, snarkos-ci1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-07-13
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --lib

      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: git-snarkos # Optional. (defaults to webhook)
        uses: 8398a7/action-slack@v3.5.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)

#  test-ga:
#    name: Check Tests (Simple)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install Rust (nightly)
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          override: true
#
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all --lib

  test-wasm:
    name: Check Tests (Wasm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Test
        run: |
          cd toolkit
          wasm-pack test --node
#          cargo test --target wasm32-unknown-unknown --features wasm

      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: git-snarkos # Optional. (defaults to webhook)
        uses: 8398a7/action-slack@v3.5.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
