name: Sync snarkOS Documentation

on:
  push:
    paths:
      - '**/*.md'
    branches-ignore:
      - master
  pull_request:
    paths:
      - '**/*.md'
    branches-ignore:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1

      - name: Sync repository
        run: |
          curl \
            -X POST \
            -u "${{ secrets.SYNC_USERNAME }}:${{ secrets.SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ secrets.SYNC_ORGANIZATION }}/${{ secrets.SYNC_APPLICATION }}/dispatches \
            -d '{"event_type":"sync-snarkos-documentation", "client_payload": { "branch": "${ BRANCH_NAME }" }}'
