[package]
name = "snarkos-models"
version = "0.8.0"
authors = ["Michael Beller", "Collin Chin", "Raymond Chu", "Matthew Green", "Ian Miers", "Howard Wu"]
description = "Models for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-errors = { path = "../errors", version = "0.8.0", default-features = false, features = ["algorithms", "gadgets"] }
snarkos-utilities = { path = "../utilities" }

derivative = { version = "1" }
failure = { version = "0.1" }
rand = { version = "0.7", default-features = false, optional = true }
rand_xorshift = { version = "0.2", default-features = false, optional = true }
smallvec = { version = "1.2", optional = true }

#
# Each module in `snarkos-models` is guarded by a feature flag to minimize compilation resources.
# To include any one of the modules in `snarkos-models`, simply include its corresponding feature flag.
#
# For example, to include models for `snarkos-algorithms`, add the "algorithm" feature as follows:
# snarkos-models = { version = "x.x.x", default-features = false, features = ["algorithms"] }
#
[features]
default = []
algorithms = []
curves = ["rand", "rand_xorshift"]
dpc = []
gadgets = ["rand_xorshift", "smallvec"]
